### ISSUE TITLE
Include properly in Debian?

### ISSUE THREAD

**Issue by scfc** [GPCsolutions/debian-python3-oursql#1]
I have filed a [Request for Package](https://bugs.debian.org/786796) to include `oursql` in Debian.  Do you want to push your work here into Debian?

**Comment by rdoursenaud** [comment]
Unfortunately this package is autogenerated and does not comply with Debian packaging policies.

This was made for a one-shot need and I have no interrest in maintening it.

Feel free to use this as a base though, that's why I made it publically available.

**Comment by scfc** [comment]
Merci!
